[package]
name = "game_sdk"
version = "0.1.0"
authors = ["Niko Ha√ü <nikohass571@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }
